name: Build simple logger

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.8"
      
      - name: Install linux dependancies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
          platformio update
      
      - name: Build Simple Logger
        run: platformio run

      - name: Create Release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.CI_TOKEN }}
          file: .pio/build/*/firmware.bin
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true


